

' ,
     'https://eu2.proxysite.com/process.php?d=' ,
     'https://eu3.proxysite.com/process.php?d=' ,
     'https://eu4.proxysite.com/process.php?d=' ,
     'https://eu5.proxysite.com/process.php?d=' ,
     'https://eu6.proxysite.com/process.php?d=' ,
     'https://eu7.proxysite.com/process.php?d=' ,
     'https://eu8.proxysite.com/process.php?d=' ,
     'https://eu9.proxysite.com/process.php?d=' ,
     'https://eu10.proxysite.com/process.php?d=' ,
     'https://us1.proxysite.com/process.php?d=' ,
     'https://us2.proxysite.com/process.php?d=' ,
     'https://us3.proxysite.com/process.php?d=' ,
     'https://us4.proxysite.com/process.php?d=' ,
     'https://us5.proxysite.com/process.php?d=' ,
     'https://us6.proxysite.com/process.php?d=' ,
     'https://us7.proxysite.com/process.php?d=' ,
     'https://us8.proxysite.com/process.php?d=' ,
     'https://us9.proxysite.com/process.php?d=' ,
     'https://us10.proxysite.com/process.php?d=' ,
     'https://us11.proxysite.com/process.php?d=' ,
     'https://us12.proxysite.com/process.php?d=' ,
     'https://us13.proxysite.com/process.php?d=' ,
     'https://us14.proxysite.com/process.php?d=' ,
     'https://us15.proxysite.com/process.php?d=' ,
     'https://divine.graphics/proxy.php?' ,
     'https://www.localizaip.com.br/localizar-ip.php?ip=' ,
     'http://www.meuenderecoip.com/localizar-ip.php?ip=' ,
     'https://website-down.com/' ,
     'http://proxy.clgt.net/proxy.php/' ,
     'https://www.pinterest.com/pin/create/button/?url=' ,
     'https://www.reddit.com/login/?dest=' ,
     'https://www.reddit.com/submit?url=' ,
     'https://www.filterbypass.me/s.php?k=' ,
     'https://www.filterbypass.me/?url=' ,
     'https://quantrimang.com/url?q=' ,
     'https://learnsql.xyz/chuyen-huong/?url=' ,
     'https://user.gtarcade.com/site/login?rurl=' ,
     'http://e9geolgzk6.com/iuqasfg3?dbqfdh=34&refer=' ,
     'https://iplookup.flagfox.net/?host=' ,
     'https://foradoar.org/' ,
     'https://duckduckgo.com/' ,
     'https://www.google.com/' ,
     'https://www.youtube.com' ,
     'http://www.google.com/?q=' ,
     'https://www.responsinator.com/?url=' ,
     'https://king.host/wiki/?url=' ,
     'https://website.grader.com/results/' ,
     'https://sitecheck.sucuri.net/results/' ,
     'https://www.ssllabs.com/ssltest/analyze.html?d=' ,
     'https://transparencyreport.google.com/safe-browsing/search?url=' ,
     'https://www.webpagetest.org/?url=' ,
     'https://www.hostinger.com.br/tutoriais/?url=' ,
     'https://www.sslshopper.com/ssl-checker.html#hostname=' ,
     'https://safeweb.norton.com/report/show?url=' ,
     'http://www.usatoday.com/search/results?q=' ,
     'http://engadget.search.aol.com/search?q=' ,
     'http://validator.w3.org/check?uri=' ,
     'http://www.facebook.com/sharer/sharer.php?u=' ,
     'http://downforeveryoneorjustme.com/' ,
     'http://network-tools.com/default.asp?prog=ping&host=' ,
     'http://network-tools.com/default.asp?prog=trace&host=' ,
     'http://network-tools.com/default.asp?prog=network&host=' ,
     'https://domainr.com/?q=' ,
     'https://down.is/' ,
     'http://whois.domaintools.com/' ,
     'https://downforeveryoneorjustme.com/' ,
     'https://www.webhostinghero.com/#' ,
     'https://www.whoishostingthis.com/#search=' ,
     'https://ping.eu/port-chk/?url=' ,
     'https://www.host-tracker.com/?url=' ,
     'http://hostchecker.net/?url=' ,
     'https://hostingchecker.com/?url=' ,
     'https://www.virustotal.com/vi/?url=' ,
     'http://tainhachay.mobi/?url=' ,
     'http://trangtainhac.info/?url=' ,
     'http://www.phimmoi.net/?url=' ,
     'https://website.informer.com/' ,
     'https://tainhacvemay.net/?url=' ,
     'https://nhacvietnam.mobi/?url=' ,
     'https://waptainhac.net/?url=' ,
     'https://trangtainhac.net/?url=' ,
     'https://trangtainhac.com/?url=' ,
     'https://yamcode.com/?url=' ,
     'http://network-tools.com/default.asp?prog=ping&host=' ,
     'http://network-tools.com/default.asp?prog=trace&host=' ,
     'http://network-tools.com/default.asp?prog=network&host=' ,
     'http://waptaiaz.com/tai-nhac-mp3/web/artist/list/quality=1&ver=w/?url=' ,
     'https://www.facebook.com/sharer/sharer.php?u=https://www.facebook.com/sharer/sharer.php?u=' ,
     'http://www.google.com/?q=' ,
     'https://www.facebook.com/l.php?u=https://www.facebook.com/l.php?u=' ,
     'https://drive.google.com/viewerng/viewer?url=' ,
     'http://www.google.com/translate?u=' ,
     'https://developers.google.com/speed/pagespeed/insights/?url=' ,
     'http://help.baidu.com/searchResult?keywords=' ,
     'http://www.bing.com/search?q=' ,
     'https://add.my.yahoo.com/rss?url=' ,
     'https://play.google.com/store/search?q=' ,
     'http://yandex.ru/yandsearch?text=%D1%%D2%?=g.sql()81% ..' ,
     'http://vk.com/profile.php?redirect=' ,
     'http://www.usatoday.com/search/results?q=' ,
     'http://engadget.search.aol.com/search?q=query?=query= ..' ,
     'https://v1.push-time.com/notifications/pub2/cpm/3/infinity/index.html?p1=' ,
     'https://browsergames2018.com/bestgames/custom/anime/oven/hentai/index.php?country_code=VN&p1=' ,
     'https://www.google.ru/#hl=ru&newwindow=1?&saf..,or.r_gc.r_pw=?.r_cp.r_qf.,cf.osb&fp=fd2cf4e896a87c19&biw=1680&bih=882' ,
     'https://www.google.ru/#hl=ru&newwindow=1&safe..,or.r_gc.r_pw.r_cp.r_qf.,cf.osb&fp=fd2cf4e896a87c19&biw=1680&bih=925' ,
     'http://yandex.ru/yandsearch?text=' ,
     'https://www.google.ru/#hl=ru&newwindow=1&safe..,iny+gay+q=pcsny+=;zdr+query?=poxy+pony&gs_l=hp.3.r?=.0i19.505.10687. 0.10963.33.29.4.0.0.0.242.4512.0j26j3.29.0.clfh..0.0.dLyKYyh2BUc & pbx = 1 & bav = on.2, or.r_gc.r_pw.r_cp.r_qf., Cf.osb bi & fp? =? Fd2cf4e89 ' ,
     'http://go.mail.ru/search?mail.ru=1&q=' ,
     'http://nova.rambler.ru/search?=btnG?=%D0?2?%D0?2?%=D0 ..' ,
     'http://ru.wikipedia.org/wiki/%D0%9C%D1%8D%D1%x80_%D0% ..' ,
     'http://ru.search.yahoo.com/search;_yzt=?=A7x9Q.bs67zf ..' ,
     'http://ru.search.yahoo.com/search;?_query?=l%t=?=?A7x ..' ,
     'http://go.mail.ru/search?gay.ru.query=1&q=?abc.r ..' ,
     'https://www.google.us/#hl=vi-US?&newwindow=1&safe=off&sclient=psy=?-ab&query=%D0%BA%D0%B0%Dq=?0%BA+%D1%83% () _D0% B1% D0% B = 8% D1% 82% D1% 8C +% D1% 81bvc? & = Query &% D0% BB% D0% BE% D0% BD% D0% B0q + =% D1% 80% D1 % 83% D0% B6% D1% 8C% D0% B5 +% D0% BA% D0% B0% D0% BA% D0% B0% D1% 88% D0% BA% D0% B0 +% D0% BC% D0% BE % D0% BA% D0% B0% D1% 81% D0% B8% D0% BD% D1% 8B +% D1% 87% D0% BB% D0% B5% D0% BD & oq = q =% D0% BA% D0% B0% D0% BA +% D1% 83% D0% B1% D0% B8% D1% 82% D1% 8C +% D1% 81% D0% BB% D0% BE% D0% BD% D0% B0 +% D1% 80% D1% 83% D0% B6% D1% 8C% D0% B5 +% D0% BA% D0% B0% D0% BA% D0% B0% D1% 88% D0% BA% D0% B0 +% D0% BC% D0% BE% D0% BA% D1% DO% D2% D0% B0% D1% 81% D0% B8% D0% BD% D1% 8B +?% D1% 87% D0% BB% D0% B5% D0% BD & gs_l = hp .3 ... 192787.206313.12.206542.48.46.2.0.0.0.190.7355.0j43.45.0.clfh..0.0.ytz2PqzhMAc & pbx = 1 & bav = on.2, or.r_gc.r_pw.r_cp.r_qf., Cf.osb6a87f19e = 1680 & bih =? 882 ' ,
     'http://nova.rambler.ru/search?btnG=%D0%9D%?D0%B0%D0%B ..' ,
     'http://www.google.ru/url?sa=t&rct=?j&q=&e ..' ,
     'http://help.baidu.com/searchResult?keywords=' ,
     'http://www.bing.com/search?q=' ,
     'https://www.yandex.com/yandsearch?text=' ,
     'https://duckduckgo.com/?q=' ,
     'http://www.ask.com/web?q=' ,
     'http://search.aol.com/aol/search?q=' ,
     'https://www.om.nl/vaste-onderdelen/zoeken/?zoeken_term=' ,
     'https://drive.google.com/viewerng/viewer?url=' ,
     'http://validator.w3.org/feed/check.cgi?url=' ,
     'http://host-tracker.com/check_page/?furl=' ,
     'http://www.online-translator.com/url/translation.aspx?direction=er&sourceURL=' ,
     'https://jigsaw.w3.org/css-validator/validator?uri=' ,
     'https://add.my.yahoo.com/rss?url=' ,
     'http://engadget.search.aol.com/search?q=' ,
     'https://steamcommunity.com/market/search?q=' ,
     'http://filehippo.com/search?q=' ,
     'http://www.topsiteminecraft.com/site/pinterest.com/search?q=' ,
     'http://eu.battle.net/wow/en/search?q=' ,
     'http://engadget.search.aol.com/search?q=' ,
     'http://careers.gatesfoundation.org/search?q=' ,
     'http://techtv.mit.edu/search?q=' ,
     'http://www.ustream.tv/search?q=' ,
     'http://www.ted.com/search?q=' ,
     'http://funnymama.com/search?q=' ,
     'http://itch.io/search?q=' ,
     'http://jobs.rbs.com/jobs/search?q=' ,
     'http://taginfo.openstreetmap.org/search?q=' ,
     'http://www.baoxaydung.com.vn/news/vn/search&q=' ,
     'https://play.google.com/store/search?q=' 
